### ISSUE TITLE
Google Drive doesn't work?

### ISSUE THREAD

**Issue by mamaruo** [btmluiz/cloudbackup#4]
When I enable the Google Drive in the config, nothing shows in the setting screen. 
Game version: 1.19.2
Mod version: 1.0.5
![image](https://github.com/btmluiz/cloudbackup/assets/37480168/e386d75d-85dd-4f44-b3e3-9f89859ac5e8)
```yml
autoBackup: true
backupInterval: 30
backupWhenExit: true
broadCastBackupMessage: true
enableBackup: true
googleDrive:
  enabled: true
  makeWorldDir: true
  uploadDir: cloudbackups
outputPath: cloudbackups
```
